//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.27 at 01:18:00 PM CDT 
//


package externo.soap.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the externo.soap.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SolicitudPago_QNAME = new QName("http://telefonia.com/ProveedoresTelefonia.xsd", "SolicitudPago");
    private final static QName _ProveedorTelefonia_QNAME = new QName("http://telefonia.com/ProveedoresTelefonia.xsd", "ProveedorTelefonia");
    private final static QName _Plan_QNAME = new QName("http://telefonia.com/ProveedoresTelefonia.xsd", "Plan");
    private final static QName _RespuestaPago_QNAME = new QName("http://telefonia.com/ProveedoresTelefonia.xsd", "RespuestaPago");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: externo.soap.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SolicitudPago }
     * 
     */
    public SolicitudPago createSolicitudPago() {
        return new SolicitudPago();
    }

    /**
     * Create an instance of {@link ProveedorTelefonia }
     * 
     */
    public ProveedorTelefonia createProveedorTelefonia() {
        return new ProveedorTelefonia();
    }

    /**
     * Create an instance of {@link Plan }
     * 
     */
    public Plan createPlan() {
        return new Plan();
    }

    /**
     * Create an instance of {@link RespuestaPago }
     * 
     */
    public RespuestaPago createRespuestaPago() {
        return new RespuestaPago();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SolicitudPago }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://telefonia.com/ProveedoresTelefonia.xsd", name = "SolicitudPago")
    public JAXBElement<SolicitudPago> createSolicitudPago(SolicitudPago value) {
        return new JAXBElement<SolicitudPago>(_SolicitudPago_QNAME, SolicitudPago.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProveedorTelefonia }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://telefonia.com/ProveedoresTelefonia.xsd", name = "ProveedorTelefonia")
    public JAXBElement<ProveedorTelefonia> createProveedorTelefonia(ProveedorTelefonia value) {
        return new JAXBElement<ProveedorTelefonia>(_ProveedorTelefonia_QNAME, ProveedorTelefonia.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Plan }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://telefonia.com/ProveedoresTelefonia.xsd", name = "Plan")
    public JAXBElement<Plan> createPlan(Plan value) {
        return new JAXBElement<Plan>(_Plan_QNAME, Plan.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RespuestaPago }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://telefonia.com/ProveedoresTelefonia.xsd", name = "RespuestaPago")
    public JAXBElement<RespuestaPago> createRespuestaPago(RespuestaPago value) {
        return new JAXBElement<RespuestaPago>(_RespuestaPago_QNAME, RespuestaPago.class, null, value);
    }

}
